
name: Helloworld(Atividade 2 Actions vfarina)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  WORKFLOW_VADER: 'WORKFLOW DO VADER'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 12
      JOB_VADER: 'job do VADER'
      
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2.3.4
    
    - name: Upload do artefato do VADER
      uses: actions/upload-artifact@v2.2.3
      with:
        name: app-do-vader
        path: .
        if-no-files-found: error
        retention-days: 1
